### ISSUE TITLE
Long short ratio historical

### ISSUE THREAD

**Issue by cunhasdepedra** [binance/binance-futures-connector-python#105]
Hello, 

Does the owner of this lib can tell if his long short ratio data extends beyond 30 days? Binance endpoint doesn't give more than 30 days which means that the only way to fetch old data is by storing it. Wanted to know if he is storing etc.

**Comment by aisling-2** [comment]
This project is purely a connector to the API endpoints, there's no storage of any data. 
If https://binance-docs.github.io/apidocs/futures/en/#top-trader-long-short-ratio-accounts says "Only the data of the latest 30 days is available.", then that's also the expected behavior when using the method that calls the related endpoint.
