### ISSUE TITLE
get open orders should not require an order id

### ISSUE THREAD

**Issue by shep-analytics** [binance/binance-futures-connector-python#72]

**Comment by jonte-z** [comment]
Hi,
The code that is there for `get_open_orders` (`/fapi/v1/openOrder` and `/dapi/v1/openOrder`) is correct. These endpoints require the existence of either `orderId` or `origClientOrderId` in order to be a valid request. The code performs a check that at least one of those 2 params exist. Additionally, the other 2 related functions (`get_orders` and `get_all_orders`) don't require an `orderId`.

From the [Documentation](https://binance-docs.github.io/apidocs/futures/en/#query-current-open-order-user_data):
<img width="679" alt="image" src="https://user-images.githubusercontent.com/114036008/218900261-76230d67-4b69-4f3a-9ecf-fd566cb063f0.png">

**Comment by AlAskalany** [comment]
The issue is about getting all open orders, not a specific order, which is a different endpoint.

[Current All Open Orders (USER_DATA)
/](https://binance-docs.github.io/apidocs/futures/en/#current-all-open-orders-user_data)

In this endpoint, the orderId is optional.

```python
def get_open_orders(
    self, symbol: str, orderId: int = None, origClientOrderId: str = None, **kwargs
):
    """
    |
    | **Query Current Open Order (USER_DATA)**
    | *Get all open orders on a symbol.*

    :API endpoint: ``GET /fapi/v1/openOrder``
    :API doc: https://binance-docs.github.io/apidocs/futures/en/#query-current-open-order-user_data

    :parameter symbol: string
    :parameter orderId: optional int
    :parameter origClientOrderId: optional int
    :parameter recvWindow: optional int; the value cannot be greater than 60000.

    **Notes**
        - Either orderId or origClientOrderId must be sent
        - If the queried order has been filled or cancelled, the error message "Order does not exist" will be returned.
    """

    url_path = "/fapi/v1/openOrder"
    params = {}

    if (orderId is None) and (origClientOrderId is None):
        check_required_parameters(
            [
                [symbol, "symbol"],
                [orderId, "orderId"],
                [origClientOrderId, "origClientOrderId"],
            ]
        )
    elif orderId:
        params = {"symbol": symbol, "orderId": orderId, **kwargs}
    else:
        params = {"symbol": symbol, "origClientOrderId": origClientOrderId, **kwargs}

    return self.sign_request("GET", url_path, params)
```
