### ISSUE TITLE
Binance API status error: 503

### ISSUE THREAD

**Issue by marcos379** [binance/binance-futures-connector-python#75]
Im facing a 503 error:
2023-01-19 03:45:36.783 ERROR: Found error. status: 503, error message:

ERROR: The request could not be satisfied
Ok im handling with it catching try/except but this code has running for months, and now its facing a 503 error, 3-4x times a day.
We are all getting this randomly or what im doing wrong?
Ps.: This error are from GET /fapi/v1/klines running in a AWS located in Tokyo.

Im thinking if i edit timeout for a longer period, perhaps will solve? NOPE IT DIDNT SOLVE
Perhaps its a common issue for AWS located at Tokyo?
Im confused.

**Comment by spring12991** [comment]
I have the same problem, the server is also in Tokyo

**Comment by marcos379** [comment]
Hi spring 12991. Yes and i still have it.
You tried anything to solve it? I mean, not solving using a try/except to catch error. 
change server locate perhaps ?

**Comment by spring12991** [comment]
In the past, we used the server in Hong Kong. This error rarely occurred, but it was more frequent when we switched to the Tokyo server. The last time this error occurred was 11 hours ago. I thought that the binance server is also in Tokyo, which would be better. It seems not at all

**Comment by 2pd** [comment]
Thanks for the feedback, it seems the glitch from the server. Please feel free to share it at dev.binance.vision or to the customer support.
I don't it is related to this library.  It is by design that this library has to throw the exception to client when seeing 5xx error.  I would suggest to try catch this error and send the request again.
